### ISSUE TITLE
"Причесать" вёрстку по БЭМу

### ISSUE THREAD

**Issue by 1vank1n** [densz7/template-BEM-#1]
Молодец! Для 1го шага, прям отлично. Всё выглядит достойно.

Давай для закрытия этого шага добавим мелкие правки:
1. Подключения `<script>...</script>` уводи перед `</body>
2. `<link href="reset.css" rel="stylesheet">` всегда подключается первым из файлов стилей. В том и смысл, что он устанавливает дефолтное поведение для всех элементов, а потом ты кастомишь блоки через свои стили.
3. С _showcase_ очень элегантное решение на css! Только почему ты плодишь столько стилей с идентификаторами `-1`, `-2`, итп. Вполне возможно сделать этот же функционал с общими стилями без индексов.
4. В `.social-icon:hover:nth-child` не корректно так делать. Поменял местами кнопки и все hover'ы сбились. Правильно дать модификаторы аля `.social-icon--facebook`.

Поправь пока это. Следующее задание напишу также как issue.

**Comment by densz7** [comment]
Выполнил все правки.
С showcase вроде все получилось, все работает, а по стилям стало проще и без индексации.

**Comment by 1vank1n** [comment]
Принято 👍
